### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by akashgoswami** [akashgoswami/ipm#3]

**Comment by danielfaust** [comment]
Which auth are you referring to? I have my IRI node's remote port password protected, and when I add --iri http://user:pass@nodeip:port I'm getting:
```
Error: Invalid Response:
    at Object.invalidResponse (/usr/lib/node_modules/iota-pm/node_modules/iota.lib.js/lib/errors/requestErrors.js:5:12)
    at makeRequest.prepareResult (/usr/lib/node_modules/iota-pm/node_modules/iota.lib.js/lib/utils/makeRequest.js:160:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/iota-pm/node_modules/iota.lib.js/lib/utils/makeRequest.js:62:25)
    at exports.XMLHttpRequest.dispatchEvent (/usr/lib/node_modules/iota-pm/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/lib/node_modules/iota-pm/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/iota-pm/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

I'm using https://github.com/goestin/iota-peer-manager though

I can confirm that when I remove the `REMOTE_AUTH = user:pass` from the `ini` file and restart the server, I am then able to use IPM. So it doesn't support password protected nodes.
